[package]
name = "elastic-tunnel-rs"
version = "0.1.0"
authors = ["Wenxuan <wenxuangm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
crossbeam = "0.7"
dotenv = "0"
structopt = "0"
